    // src/task-dependencies/task-dependencies.module.ts
    import { Module } from '@nestjs/common';
    import { TypeOrmModule } from '@nestjs/typeorm';
    import { TaskDependenciesService } from './task-dependencies.service';
    import { TaskDependenciesController } from './task-dependencies.controller'; // Generated by CLI, may be unused
    import { TaskDependency } from './entities/task-dependency.entity'; // Import the entity

    @Module({
      imports: [
          // Register the TaskDependency entity with TypeORM for this module's scope
          TypeOrmModule.forFeature([TaskDependency])
        ],
      // Include the controller generated by the CLI (remove if not creating API endpoints for dependencies)
      controllers: [TaskDependenciesController],
      // Provide the service generated by the CLI
      providers: [TaskDependenciesService],
      // Export the service and TypeOrmModule to make the service and repository
      // available to other modules that import TaskDependenciesModule (like AiAgentModule)
      exports: [TaskDependenciesService, TypeOrmModule],
    })
    export class TaskDependenciesModule {}
    