// src/users/users.module.ts
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { UsersService } from './users.service';
import { UsersController } from './users.controller'; // Generated by CLI
import { User } from './entities/user.entity';

@Module({
  imports: [TypeOrmModule.forFeature([User])], // Make User repository available
  controllers: [UsersController], // Keep or remove controller based on needs
  providers: [UsersService],
  exports: [UsersService], // Export service to be used by AuthModule later
})
export class UsersModule {}
